### ISSUE TITLE
GPUSURFFeatureMatcher.h:10:31: fatal error: opencv2/gpu/gpu.hpp

### ISSUE THREAD

**Issue by ghost** [MasteringOpenCV/code#79]
Hello,

I'm trying to compile Chapter4_StructureFromMotion. So there is updated vesrion of it wich works with OpenCV 3.0?
Thank you.

**Comment by royshil** [comment]
@peter73421 an OpenCV 3 version is in the works, and should arrive soon.
